# dev: base 그대로 사용, namespace 만 dev 로 지정
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - kafka-topic-test-order.yaml
patches:
  - target:
      kind: Service
      name: pg-external
    patch: |-
      - op: add
        path: /spec/ports/0/nodePort
        value: 30432
